### ISSUE TITLE
[Android] Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by marsgpl** [Maxim-Kolmogorov/cordova-plugin-push-notifications#18]
Hi,
First of all, great plugin!
It worked out of the box for iOS (cordova 12.0.0, cordova-ios 7.0.0, cordova-plugin-push-notifications 1.1.7, deployment-target 11.0).
I'm facing some difficulties to make it work on Android.
When app is active, notifications are received and displayed correctly - no problem.
But when app is folded and notification comes, app crashes with the following error:
```
java.lang.IllegalArgumentException: my.bundle.name.here: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
 at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
 at android.app.PendingIntent.getActivity(PendingIntent.java:444)
 at android.app.PendingIntent.getActivity(PendingIntent.java:408)
 at com.google.firebase.messaging.zzb.zza(com.google.firebase:firebase-messaging@@20.0.1:59)
 at com.google.firebase.messaging.zzd.zza(com.google.firebase:firebase-messaging@@20.0.1:33)
 at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.1:60)
 at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.1:2)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
 at java.lang.Thread.run(Thread.java:1012)
```

My configuration is:

```
cordova 12.0.0
cordova-android 12.0.0
cordova-plugin-push-notifications 1.1.7
android-compileSdkVersion 33
android-targetSdkVersion 33
com.google.firebase:firebase-bom:26.8.0
com.google.firebase:firebase-messaging:20.0.1
```

According to error message, I assume that `com.google.firebase.messaging` package is outdated and creates `PendingIntent` without necessary flag `FLAG_IMMUTABLE`

I've tried to bump firebase-bom and firebase-messaging to latest versions, but they are incompatible with plugin's platforms/android/app/src/main/kotlin/notifications/*.kt files

Is there a quick workaround for that? Or maybe I did something wrong?

**Comment by marsgpl** [comment]
ok I solved

1. bump bom
com.google.firebase:firebase-bom:26.8.0
->
com.google.firebase:firebase-bom:32.2.2

2. patch code
```diff
$ diff plugins/cordova-plugin-push-notifications/src/android/Notifications.kt platforms/android/app/src/main/kotlin/notifications/Notifications.kt
4c4,5
< import com.google.firebase.iid.FirebaseInstanceId
---
> import com.google.firebase.messaging.FirebaseMessaging
> import com.google.android.gms.tasks.OnCompleteListener
60,64c61,70
<     FirebaseInstanceId.getInstance().instanceId.addOnSuccessListener { instanceIdResult ->
<       val token = instanceIdResult.token
<       Log.d("FIREBASE TOKEN", token)
<       context.success(token)
<     }
---
>     FirebaseMessaging.getInstance().token.addOnCompleteListener(OnCompleteListener { task ->
>         if (!task.isSuccessful) {
>             Log.w(TAG, "Fetching FCM registration token failed", task.exception)
>             return@OnCompleteListener
>         }
> 
>         val token = task.result
>         context.success(token)
>         Log.d(TAG, token)
>     })
```

now it works
